sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start create an image with dockerfile"
  - docker buildx build --platform=linux/amd64 -t hwibaski/docker-react-app:nginx ./

script:
  - docker run -e CI-true hwibaski/docker-react-app:nginx npm run test -- --coverage

after_success:
  - echo "Test Success"
