sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start create an image with dockerfile"
  - docker buildx build --platform=linux/amd64 -t hwibaski/docker-react-app:dev -f Dockerfile.dev ./

script:
  - docker run -e CI=true hwibaski/docker-react-app:dev npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-2'
  app: 'docker-react-app'
  env: 'DockerReactApp-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-2-083749336129'
  bucket_path: 'docker-react-app'
  on:
    branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
